tasks:
  - name: terraform
    before: |
      source  ./install_terraform_cli
  - name: aws-cli
      source  ./install_aws_cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform